app:
  name: "project-service"
  version: "0.0.1"
database:
  uri: postgres://green:0010@crm-postgres-1:5432/gustav
http:
  port: 8012
  read_timeout: 1m
  write_timeout: 1m
  shutdown_timeout: 5s
user_service:
  api: "crm-user-service-1"
  port: "8010"