app:
  name: "auth-service"
  version: "0.0.2"
database:
  uri: postgres://green:0010@crm-postgres-1:5432/gustav
jwt:
  sign_key: "gustav"
http:
  port: 8008
  read_timeout: 1m
  write_timeout: 1m
  shutdown_timeout: 5s
jwt_service:
  api: "crm-jwt-service-1"
  port: "8009"
auth:
  signature: "gustav"